create table if not exists users (
    id bigint generated by default as identity primary key,
    email varchar(255) not null unique,
    password_hash varchar(255) not null
);

create table if not exists user_roles (
    user_id bigint not null,
    role varchar(64) not null,
    primary key (user_id, role),
    constraint fk_user_roles_user foreign key (user_id) references users(id) on delete cascade
);

create table if not exists books (
    id bigint generated by default as identity primary key,
    title varchar(255) not null,
    author varchar(255) not null,
    publication_year integer,
    genres_csv varchar(1000),
    total_copies integer,
    available_copies integer
);

create table if not exists loans (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    book_id bigint not null,
    status varchar(32),
    borrowed_at date,
    due_date date,
    returned_at date,
    constraint fk_loans_user foreign key (user_id) references users(id),
    constraint fk_loans_book foreign key (book_id) references books(id)
);

create table if not exists ratings (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    book_id bigint not null,
    score integer not null,
    constraint fk_ratings_user foreign key (user_id) references users(id),
    constraint fk_ratings_book foreign key (book_id) references books(id),
    constraint uk_ratings_user_book unique (user_id, book_id)
);

create table if not exists reviews (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    book_id bigint not null,
    text varchar(2000) not null,
    created_at timestamp,
    constraint fk_reviews_user foreign key (user_id) references users(id),
    constraint fk_reviews_book foreign key (book_id) references books(id)
);

create table if not exists refresh_tokens (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    token varchar(512) not null unique,
    expires_at timestamp,
    constraint fk_refresh_tokens_user foreign key (user_id) references users(id)
);

create table if not exists recommendation_profiles (
    id bigint generated by default as identity primary key,
    user_id bigint not null unique,
    preferred_genres_csv varchar(1000),
    constraint fk_recommendation_profiles_user foreign key (user_id) references users(id)
);

create table if not exists reservations (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    book_id bigint not null,
    status varchar(32) not null,
    created_at timestamp not null,
    notified_at timestamp,
    expires_at timestamp,
    cancelled_at timestamp,
    constraint fk_reservations_user foreign key (user_id) references users(id),
    constraint fk_reservations_book foreign key (book_id) references books(id)
);

create index if not exists idx_books_title on books(title);
create index if not exists idx_books_author on books(author);
create index if not exists idx_loans_user_id on loans(user_id);
create index if not exists idx_reservations_book_id on reservations(book_id);
